AsDOr/AsDOr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path("", include("games.urls")),
  path("home/", include("home.urls")),
  path('admin/', admin.site.urls),
]

AsDOr/games/urls.py
from django.urls import include, path
from . import views

app_name = "games"

urlpatterns = [
  path("", views.GamesIndexView.as_view(), name="index"),
  path("<int:pk>/", views.GameDetailView.as_view(), name="detail"),
  path("<user_id>/password/", views.PasswordChangingView.as_view(), name="password_change"),
  path("search/", views.search_games, name="search"),
  path('accounts/', include('django.contrib.auth.urls')),
  path("accounts/edit/", views.UserEditionView.as_view(), name="edit"),
  path("accounts/signup/", views.UserCreationView.as_view(), name="signup"),
  path("accounts/wishlist/", views.view_wishlist, name="wishlist"),
  path("accounts/wishlist/add_wishlist/<game_id>/", views.add_wishlist, name="add-wishlist"),
  path("accounts/wishlist/remove_game_wishlist/<game_id>/", views.remove_game_wishlist, name="remove-game-wishlist"),
]

AsDOr/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path("", views.index, name="index")
]

AsDOr/games/models.py
from django.utils import timezone
from django.db import models
from django.forms import ValidationError
from django.contrib.auth.models import User


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    wikipedia = models.URLField(blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Game(models.Model):
    authors = models.ManyToManyField(Author, related_name="authors")
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Award(models.Model):
    CATEGORIES = [
        ("Jeu de l'année",                              "GAME_OF_THE_YEAR"),
        ("Jeu de l'année 'Enfant'",                     "KID_GAME_OF_THE_YEAR"),
        ("Jeu de l'année 'Expert'",                     "EXPERT_GAME_OF_THE_YEAR"),
        ("Jeu de l'année 'Initié'",                     "NOOB_GAME_OF_THE_YEAR"),
        ("Prix du Jury",                                "JURY_PRIZE"),
        ("Grand Prix",                                  "BIG_PRIZE"),
        ("Mention Spéciale",                            "MENTION_SPECIALE"),
        ("Super As D'Or",                               "AS_OR_SUPER"),
        ("As D'Or",                                     "AS_OR"),
        ("As D'Or Jeu d'Imagination",                   "AS_OR_IMAGINATION"),
        ("As D'Or Jeu Vidéo",                           "AS_OR_JEU_VIDEO"),
        ("As D'Or Jeu de Convivialité",                 "AS_OR_CONVIVIALITE"),
        ("As D'Or Jeu de Stratégie",                    "AS_OR_STRATEGIE"),
        ("As D'Or Jeu d'Aventure",                      "AS_OR_AVENTUREA"),
        ("As D'Or Jeu de Simulation",                   "AS_OR_SIMULATION"),
        ("As D'Or Jeu d'Informatique",                  "AS_OR_INFORMATIQUE"),
        ("As D'Or Jeu de Lettres",                      "AS_OR_LETTRES"),
        ("As D'Or Jeu de Lettres et de Connaissances",  "AS_OR_LETTRES_CONNAISSANCES"),
        ("As D'Or Jeu Espoir",                          "AS_OR_ESPOIR"),
        ("As D'Or Jeu Junior (13 - 17 ans)",            "AS_OR_JUNIOR"),
        ("As D'Or Jeu Benjamin (4 - 7 ans)",            "AS_OR_BENJAMIN"),
        ("As D'Or Jeu Cadet (8 - 12 ans)",              "AS_OR_CADET"),
        ("As D'Or Jeu de Société",                      "AS_OR_SOCIETE"),
        ("As D'Or Jeu de Société d'Intéractif",         "AS_OR_SOCIETE_INTERACTIF"),
        ("As D'Or Jeu Joker",                           "AS_OR_JOKER"),
        ("As D'Or Prix Spécial du Jury",                "AS_OR_SPECIAL_JURY"),
        ("As D'Or Jeu de Dés",                          "AS_OR_DES"),
        ("As D'Or Jeu Innovation",                      "AS_OR_INNOVATION"),
        ("As D'Or Jeu de Tactique",                     "AS_OR_TACTIQUE"),
        ("As D'Or Jeu de Vocabulaire",                  "AS_OR_VOCABULAIRE"),
        ("As D'Or Jeu de Cartes à collectionner",       "AS_OR_CARTES_COLLECTION"),
        ("As D'Or Jeu Familial",                        "AS_OR_FAMILIALAS_OR_FAMILIAL"),
        ("As D'Or Jeu de la Décennie",                  "AS_OR_DECENNIE"),
        ("As D'Or Jeu de Réfléxion",                    "AS_OR_REFLEXION")
    ]
    year = models.CharField(max_length=4)
    category = models.CharField(choices=CATEGORIES, max_length=50)
    game = models.OneToOneField(Game, on_delete=models.CASCADE)

    def __str__(self):
        return self.category + " " + str(self.year)

    class Meta:
        # Order awards by year in descending order
        ordering = ['-year']
        # Set unique constraint on category and year to enforce one award per category per year
        constraints = [
            models.UniqueConstraint(fields=['category', 'year'], name='unique_award')
        ]

    def clean(self):
        # Check that year is an integer and falls between 1988 and the current year
        current_year = timezone.now().year
        try:
            year = int(str(self.year)[:4])
            if year < 1988 or year > current_year:
                raise ValidationError({'year': 'Year must be between 1988 and the current year.'})
        except ValueError:
            raise ValidationError({'year': 'Year must be an integer.'})

    # Use custom save method to auto-populate year if not specified
    def save(self, *args, **kwargs):
        if not self.year:
            self.year = timezone.now().date()
        super().save(*args, **kwargs)


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    games = models.ManyToManyField(Game, related_name="games")

AsDOr/games/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class EditForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

AsDOr/games/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages

from .forms import SignUpForm, EditForm, PasswordChangingForm
from .models import Award, Game, Wishlist, User
from django.contrib.auth.views import PasswordChangeView

def search_games(request):
    if request.method == "POST":
        searched = request.POST['searched']
        games = Game.objects.filter(name__contains = searched)
        return render(request,"games/search_games.html", {'searched': searched, 'games': games})
    else:
        return render(request,"games/search_games.html", {})

def remove_game_wishlist(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    wishlist = Wishlist.objects.get(user=request.user)
    wishlist.games.remove(game)
    return redirect('games:wishlist')

def add_wishlist(request, game_id):
    game = Game.objects.get(pk=game_id)
    wishlist, created = Wishlist.objects.get_or_create(pk=request.user.id)
    wishlist.games.add(game)
    return redirect('games:wishlist')

def view_wishlist(request):
    wishlist = Wishlist.objects.filter(user=request.user).first()
    games = wishlist.games.all() if wishlist else []
    return render(request, 'accounts/wishlist.html', {'games': games})

class GamesIndexView(generic.ListView):
    template_name = 'games/index.html'
    model = Award

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        awards = Award.objects.all().select_related('game').prefetch_related('game__authors')
        years = sorted(set(award.year for award in awards), reverse=True)
        games_by_year = {}
        for year in years:
            games_by_year[year] = []
            for award in awards.filter(year=year):
                game = award.game
                authors = game.authors.all()
                category = award.category
                games_by_year[year].append({'game': game, 'authors': authors, 'category': category})
        context['games_by_year'] = games_by_year
        return context

class GameDetailView(generic.DetailView):
    model = Award
    template_name = "games/detail.html"

class UserCreationView (generic.CreateView):
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy('games:login')

class UserEditionView (generic.UpdateView):
    form_class = EditForm
    template_name = "registration/edit_account.html"
    success_url = reverse_lazy('games:index')

    def get_object(self):
        return self.request.user

class PasswordChangingView(PasswordChangeView):
    form_class = PasswordChangingForm
    template_name = "registration/password_change.html"
    success_url = reverse_lazy('games:password_change_done')

AsDOr/games/templates/games/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body class="d-flex flex-column min-vh-100 text-bg-light p-3">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'games:index' %}">
                    Les As D'Or !
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="True" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username|upper }}
                                </a>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="{% url 'games:edit'%}">Profil</a></li>
                                  <li><hr class="dropdown-divider"></li>
                                  <li><a class="dropdown-item" href="{% url 'games:wishlist'%}">Wishlist</a></li>
                                </ul>
                              </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'games:logout' %}">Se déconnecter</a>
                        </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'games:signup' %}">S'enregistrer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'games:login' %}">Se connecter</a>
                            </li>
                        {% endif %}
                        </ul>
                    <form class="d-flex" role="search" method="POST" action={% url 'games:search' %}>
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" placeholder="Akropolis" aria-label="Search" name="searched">
                        <button class="btn btn-outline-info" type="submit">Recherche</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
        <footer class="mt-auto">
            <div class="p-4 text-center text-center">
                © <span id="copyright-year">2023</span> Copyright:
                <a href="{% url 'games:index' %}" class="text-reset fw-bold">Les As D'Or !</a>
                </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script>document.querySelector("#copyright-year").innerText=(new Date).getFullYear()</script>
    </body>
</html>

AsDOr/games/templates/games/detail.html
{% extends 'games/base.html' %}
{% load static %}
{% block title %}{{ award.game.name }}{% endblock title %}
{% block content %}
<div class="row text-center">
    <h1>{{ award.game.name }}</h1>
    <div class="col">
        <img src="{% static 'games/img/' %}{{award.game.id}}.jpeg" style="height:300px; width: 300px;" alt={{award.game.name}}/>

        <div>
            <p>Auteurs : {% for author in award.game.authors.all %} {{ author }}
            {% if not forloop.last %}, {% endif %}{% endfor %}</p>
        </div>
        <p>Année récompense : {{ award.year }}</p>
        <p>Catégorie récompense : {{ award.category }}</p>
        <p>Description : </p>
        {% if user.is_authenticated %}
            <a href="{% url 'games:add-wishlist' award.game.id %}" class="btn btn-dark">Ajouter à la wishlist</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

AsDOr/games/templates/games/index.html
{% extends 'games/base.html' %}
{% load static %}
{% block title %}Les As D'Or !{% endblock title %}
{% block content %}
    <h1>Liste des As D'Or </h1>
    {% for year, awards in games_by_year.items %}
        <div class="shadow-lg p-3 my-5 bg-body rounded text-center"><h2>{{ year }}</h2></div>
        <div class="row row-cols-2 row-cols-md-2 row-cols-lg-4 g-4">
            {% for award in awards %}
                <div class="col">
                    <div class="card border-dark text-center h-100">
                        <img class="rounded mx-auto d-block" style="height: 150px; width: 150px;" src="{% static 'games/img/' %}{{award.game.id}}.jpeg" alt='{{award.game.name}}'>
                        <div class="card-body">
                            <h5 class="card-title">{{ award.game.name }}</h5>
                            <p class="card-text">
                                {{ award.category }}
                            </p>
                            <p class="card-text">
                                {% for author in award.game.authors.all %}
                                {{ author }}{% if not forloop.last %}<br>{% endif %}
                                {% endfor %}
                            </p>

                        </div>
                        <div class="card-footer">
                            {% if user.is_authenticated %}
                                <a href="{% url 'games:add-wishlist' award.game.id %}" class="btn btn-dark">Ajouter à la wishlist</a>
                            {% endif %}
                            <a href="{% url 'games:detail' award.game.id %}" class="btn btn-dark">Détail</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock content%}

AsDOr/games/templates/games/search_games.html
{% extends 'games/base.html' %}
{% block title %}Research{% endblock title %}
{% block content %}
    {% if searched %}<h1>Le résultat de la recherche : {{ searched|upper }}</h1>
        <p>
            {% for game in games %}
                <a href="{% url 'games:detail' game.id %}">{{ game }}</a>
            {% endfor %}
        </p>
    {% else %}
        <h1>Vous n'avez pas saisi la valeur de votre recherche</h1>
    {% endif %}
{% endblock content %}